name: Manually retrigger the update of the OCM CLI documentation

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Which version (e.g. v0.42.0) do you want to publish?
        required: true
        default: ''

jobs:
  retrigger:
    name: Create new "Release Publish Event"
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
    - name: Ensure proper version
      run: |
        if ![ -n "${{ github.event.inputs.version }}" ]; then
          echo "Version not provided"
          exit 1
        fi
        echo "RELEASE_VERSION=$(echo ${{ github.event.inputs.version }} | tr -d ['v'])" >> $GITHUB_ENV
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.OCMBOT_APP_ID }}
        private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
    - name: Publish Event
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}
        repository: hilmarf/ocm-website
        event-type: ocm-cli-release
        client-payload: '{"tag": "${{ env.RELEASE_VERSION }}"}'
