name: Manually retrigger the update of the OCM CLI documentation

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Which version (e.g. v0.42.0) do you want to publish?
        required: true
        default: ''

jobs:
  retrigger:
    name: Create new "Release Publish Event"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.OCMBOT_APP_ID }}
        private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
    - name: Ensure proper version
      run: |
        if ![ -n "${{ github.event.inputs.version }}" ]; then
          echo "Version not provided"
          exit 1
        fi
        # let's check if the version is already published
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/open-component-model/ocm/releases > versions.txt
        grep -Fxq '${{ github.event.inputs.version }}' versions.txt && echo "Version found" || echo "Version not found" && exit 1
        echo "RELEASE_VERSION=$(echo ${{ github.event.inputs.version }} )" >> $GITHUB_ENV
    - name: Publish Event
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}
        repository: hilmarf/ocm-website
        event-type: ocm-cli-release
        client-payload: '{"tag": "${{ env.RELEASE_VERSION }}"}'
